/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock_management;

import com.stock.db.DB;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author pasindu hathurushigh
 */
public class CompanyPanel extends javax.swing.JPanel {

    SupplierCompanyManagement supCompanyMgt;

    /**
     * Creates new form CompanyPanel
     */
    public CompanyPanel(SupplierCompanyManagement supCompMgt) {
        initComponents();
        this.supCompanyMgt = supCompMgt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        txt_companyname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_company_contact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rad_active = new javax.swing.JRadioButton();
        rad_inactive = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setText("Company Name");

        txt_companyname.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setText("Company Contact No.");

        txt_company_contact.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setText("Status");

        buttonGroup1.add(rad_active);
        rad_active.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rad_active.setSelected(true);
        rad_active.setText("Active");

        buttonGroup1.add(rad_inactive);
        rad_inactive.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rad_inactive.setText("Inactive");

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rad_active)
                                .addGap(70, 70, 70)
                                .addComponent(rad_inactive))
                            .addComponent(txt_companyname)
                            .addComponent(txt_company_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_companyname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_company_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_active)
                    .addComponent(rad_inactive)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txt_companyname.getText().equals("") && !txt_company_contact.getText().equals("")) {
            try {
                DB.push("INSERT INTO company(`company_name`,`contactno`) VALUES('"
                        + txt_companyname.getText().trim().toUpperCase() + "','"
                        + txt_company_contact.getText() + "')");
                ResultSet rs = DB.search("SELECT MAX(`company_id`) AS maxid FROM company");
                if (rs.next()) {
                    String company_id = rs.getString("maxid");
                    String company_name = txt_companyname.getText();
                    supCompanyMgt.loadBranchPanel(company_id, company_name);
                }
            } catch (java.sql.SQLIntegrityConstraintViolationException e) {
                try {
                    int status = (rad_active.isSelected()) ? 1 : 0;
                    DB.push("UPDATE company SET `contactno`='"
                            +txt_company_contact.getText()+"',`status`='"
                            +status+"' WHERE `company_name`='"+
                            txt_companyname.getText().trim().toUpperCase()+"'");
                    JOptionPane.showMessageDialog(this, "Company already registered from this name. Details updated!");
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } catch (Exception e) {
                e.printStackTrace();

            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all mandatory fields!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rad_active;
    private javax.swing.JRadioButton rad_inactive;
    private javax.swing.JTextField txt_company_contact;
    private javax.swing.JTextField txt_companyname;
    // End of variables declaration//GEN-END:variables

}
