/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock_management;

import com.stock.db.DB;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pasindu hathurushigh
 */
public class CompanyBranchPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompanyBranchPanel
     */
    public CompanyBranchPanel() {
        initComponents();
        loadCompany();
    }

    CompanyBranchPanel(String company_id, String company_name) {
        this();
        combo_company.setSelectedItem(company_id + "-" + company_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        combo_company = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        combo_branch = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_branchName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_contactno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_addline1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_addline2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_addline3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        rad_active = new javax.swing.JRadioButton();
        rad_inactive = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText("Company Name");

        combo_company.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        combo_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_companyActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setText("Branches");

        combo_branch.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        combo_branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_branchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Branch Name");

        txt_branchName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Branch Contact No.");

        txt_contactno.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("Address Line1");

        txt_addline1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("Address Line2");

        txt_addline2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("Address Line3");

        txt_addline3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rad_active);
        rad_active.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rad_active.setSelected(true);
        rad_active.setText("Active");

        buttonGroup1.add(rad_inactive);
        rad_inactive.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rad_inactive.setText("Inactive");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_branch, 0, 467, Short.MAX_VALUE)
                            .addComponent(txt_contactno)
                            .addComponent(txt_branchName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(24, 24, 24)
                        .addComponent(combo_company, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(txt_addline1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rad_active)
                                .addGap(82, 82, 82)
                                .addComponent(rad_inactive)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_addline2)
                            .addComponent(txt_addline3))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_company, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(combo_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_branchName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_contactno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_addline1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_addline2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_addline3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_active)
                    .addComponent(rad_inactive)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!txt_branchName.getText().equals("") && !txt_contactno.getText().equals("")
                && !txt_addline1.getText().equals("") && !txt_addline2.getText().equals("")) {
            try {
                DB.push("INSERT INTO address(`address_line1`,`address_line2`,`address_line3`) VALUES('"
                        + txt_addline1.getText().trim() + "','"
                        + txt_addline2.getText().trim() + "','"
                        + txt_addline3.getText().trim() + "')");
                ResultSet rs = DB.search("SELECT `id` FROM address WHERE `address_line1`='"
                        + txt_addline1.getText() + "' AND `address_line2`='"
                        + txt_addline2.getText() + "' AND `address_line3`='"
                        + txt_addline3.getText() + "'");
                if (rs.next()) {
                    DB.push("INSERT INTO branch(`company_id`,`branch_name`,`branch_contactno`,`address_id`)"
                            + " VALUES('" + combo_company.getSelectedItem().toString().split("-")[0] + "','"
                            + txt_branchName.getText() + "','" + txt_contactno.getText() + "','"
                            + rs.getString("id") + "')");
                    JOptionPane.showMessageDialog(this, "Branch registered!");
                    clearFields();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all mandatory fields!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combo_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_companyActionPerformed
        try {
            ResultSet rs = DB.search("SELECT `branch_id`,`branch_name` FROM branch WHERE `company_id`='"
                    + combo_company.getSelectedItem().toString().split("-")[0] + "' AND `status`='1'");
            Vector v = new Vector();
            while (rs.next()) {
                v.add(rs.getString("branch_id") + "-" + rs.getString("branch_name"));
            }
            combo_branch.setModel(new DefaultComboBoxModel<>(v));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_combo_companyActionPerformed

    private void combo_branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_branchActionPerformed
        try {
            ResultSet rs = DB.search("SELECT * FROM branch b INNER JOIN address a ON a.`id`=b.`address_id`"
                    + " WHERE `branch_id`='" + combo_branch.getSelectedItem().toString().split("-")[0] + "'");
            if (rs.next()) {
                txt_branchName.setText(rs.getString("branch_name"));
                txt_branchName.setText(rs.getString("branch_contactno"));
                txt_addline1.setText(rs.getString("address_line1"));
                txt_addline2.setText(rs.getString("address_line2"));
                txt_addline3.setText(rs.getString("address_line3"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_combo_branchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ResultSet rs = DB.search("SELECT `address_id` FROM branch WHERE `branch_id`='"
                    + combo_branch.getSelectedItem().toString().split("-")[0] + "'");
            if (rs.next()) {
                DB.push("UPDATE address SET `address_line1`='"
                        + txt_addline1.getText() + "',`address_line2`='"
                        + txt_addline2.getText() + "',`address_line3`='"
                        + txt_addline3.getText() + "' WHERE `id`='"
                        + rs.getString("address_id") + "'");
            }
            int status = (rad_active.isSelected()) ? 1 : 0;
            DB.push("UPDATE branch SET `branch_name`='"
                    + txt_branchName.getText() + "',`branch_contactno`='"
                    + txt_contactno.getText() + "',`status`='" + status + "' WHERE `branch_id`='"
                    + combo_branch.getSelectedItem().toString().split("-")[0] + "'");
            JOptionPane.showMessageDialog(this, "Branch Updated!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_branch;
    private javax.swing.JComboBox<String> combo_company;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rad_active;
    private javax.swing.JRadioButton rad_inactive;
    private javax.swing.JTextField txt_addline1;
    private javax.swing.JTextField txt_addline2;
    private javax.swing.JTextField txt_addline3;
    private javax.swing.JTextField txt_branchName;
    private javax.swing.JTextField txt_contactno;
    // End of variables declaration//GEN-END:variables

    private void loadCompany() {
        try {
            ResultSet rs = DB.search("SELECT `company_id`,`company_name` FROM company WHERE `status`='1'");
            Vector v = new Vector();
            while (rs.next()) {
                v.add(rs.getString("company_id") + "-" + rs.getString("company_name"));
            }
            combo_company.setModel(new DefaultComboBoxModel<>(v));
            combo_company.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearFields() {
        txt_branchName.setText(null);
        txt_contactno.setText(null);
        txt_addline1.setText(null);
        txt_addline2.setText(null);
        txt_addline3.setText(null);
        combo_company.setSelectedIndex(0);
    }
}
